$( document ).ready(function() {
		$("#form").hide();
		$("#form1").hide();
		$("#form2").hide();
		$("#form8").hide();
		$("#verequipo").hide();
		$("#form3").hide();
		$("#form6").hide();

	$("#ra").click(function(){
		$("#imagen").hide();
		$("#form").hide();
		$("#form1").show();
		$("#form2").hide();
		$("#form8").hide();
		$("#form3").hide();
		$("#form6").hide();
	});
	$("#ru").click(function(){
		$("#form").show();
		$("#form1").hide();
		$("#imagen").hide();
		$("#form2").hide();
		$("#form8").hide();
		$("#form3").hide();
		$("#form6").hide();
	});

	$("#h").click(function(){
		$("#form").hide();
		$("#form1").hide();
		$(".imagen").show();
		$("#form2").hide();
		$("#form8").hide();
		$("#form3").hide();
		$(".imagen").css({"width":"30em","height":"30em"});
		$("#form6").hide();
	});
	$("#is").click(function(){
		$("#form").hide();
		$("#form1").hide();
		$("#imagen").hide();
		$("#form2").show();
		$("#form8").show();
		$("#form6").hide();
	});
	$("#RE").click(function(){
		$("#form").show();
		$("#form1").hide();
		$("#verequipo").hide();
		$("#form2").show();
		$(".ocultar").hide();
		$(".imagen").css({"width":"20em","height":"20em","margin-top":"2em"});
	});

	$("#RA").click(function(){
		$("#form").hide();
		$("#form1").show();
		$("#verequipo").hide();
		$("#form2").hide();
		$("#form8").hide();
		$(".ocultar").hide();
		$("#form6").hide();
		$(".imagen").css({"width":"20em","height":"20em","margin-top":"2em"});
	});

	$("#verE").click(function(){
		$("#form").hide();
		$("#verequipo").show();
		$("#form1").hide();
		$("#form2").hide();
		$("#form6").hide();
		$(".imagen").css({"width":"20em","height":"20em","margin-top":"2em"});
	});

	$("#RC").click(function(){
		$("#form").hide();
		$("#verequipo").hide();
		$("#form1").hide();
		$("#form2").hide();
		$("#form3").show();
		$("#form6").hide();
		$(".imagen").css({"width":"20em","height":"20em","margin-top":"2em"});
	});

	$("#RP").click(function(){
		$("#form").hide();
		$("#verequipo").hide();
		$("#form1").hide();
		$("#form2").hide();
		$("#form3").hide();
		$("#form6").show();
		$(".imagen").css({"width":"20em","height":"20em","margin-top":"2em"});
	});

});