-- MySQL Script generated by MySQL Workbench
-- 05/25/16 09:51:31
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`UNIVERSIDAD`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`UNIVERSIDAD` (
  `idUniversidad` INT AUTO_INCREMENT NOT NULL,
  `nombreU` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `calleU` VARCHAR(45) NOT NULL,
  `coloniaU` VARCHAR(45) NOT NULL,
  `delegacionU` VARCHAR(45) NOT NULL,
  `password` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idUniversidad`),
  UNIQUE INDEX `nombreU_UNIQUE` (`nombreU` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EQUIPO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EQUIPO` (
  `clvEquipo` INT AUTO_INCREMENT NOT NULL,
  `nombreE` VARCHAR(45) NOT NULL,
  `numIntegrantes` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `UNIVERSIDAD_idUniversidad` INT NOT NULL,
  PRIMARY KEY (`clvEquipo`),
  UNIQUE INDEX `status_UNIQUE` (`status` ASC),
  UNIQUE INDEX `clvEquipo_UNIQUE` (`clvEquipo` ASC),
  INDEX `fk_EQUIPO_UNIVERSIDAD_idx` (`UNIVERSIDAD_idUniversidad` ASC),
  CONSTRAINT `fk_EQUIPO_UNIVERSIDAD`
    FOREIGN KEY (`UNIVERSIDAD_idUniversidad`)
    REFERENCES `mydb`.`UNIVERSIDAD` (`idUniversidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PARTICIPANTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PARTICIPANTE` (
  `EQUIPO_clvEquipo` INT AUTO_INCREMENT NOT NULL,
  `clvPart` INT NOT NULL,
  `nombrePila` VARCHAR(45) NOT NULL,
  `apPatP` VARCHAR(45) NOT NULL,
  `apMatP` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`EQUIPO_clvEquipo`, `clvPart`),
  INDEX `fk_PARTICIPANTE_EQUIPO1_idx` (`EQUIPO_clvEquipo` ASC),
  CONSTRAINT `fk_PARTICIPANTE_EQUIPO1`
    FOREIGN KEY (`EQUIPO_clvEquipo`)
    REFERENCES `mydb`.`EQUIPO` (`clvEquipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PACA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PACA` (
  `numPaca` INT AUTO_INCREMENT NOT NULL,
  `status` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`numPaca`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PARTIDO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PARTIDO` (
  `clvPartido` INT AUTO_INCREMENT NOT NULL,
  `fecha` VARCHAR(45) NOT NULL,
  `numPacas` INT NOT NULL,
  PRIMARY KEY (`clvPartido`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RONDA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`RONDA` (
  `numRonda` INT AUTO_INCREMENT NOT NULL,
  `ubicacion` VARCHAR(45) NOT NULL,
  `PARTIDO_clvPartido` INT NOT NULL,
  PRIMARY KEY (`numRonda`),
  INDEX `fk_RONDA_PARTIDO1_idx` (`PARTIDO_clvPartido` ASC),
  CONSTRAINT `fk_RONDA_PARTIDO1`
    FOREIGN KEY (`PARTIDO_clvPartido`)
    REFERENCES `mydb`.`PARTIDO` (`clvPartido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TIRO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TIRO` (
  `RONDA_numRonda` INT AUTO_INCREMENT NOT NULL,
  `PARTICIPANTE_EQUIPO_clvEquipo` INT NOT NULL,
  `PARTICIPANTE_clvPart` INT NOT NULL,
  `puntos` INT NOT NULL,
  `numTiro` INT NOT NULL,
  `empate` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`RONDA_numRonda`, `PARTICIPANTE_EQUIPO_clvEquipo`, `PARTICIPANTE_clvPart`),
  INDEX `fk_TIRO_PARTICIPANTE1_idx` (`PARTICIPANTE_EQUIPO_clvEquipo` ASC, `PARTICIPANTE_clvPart` ASC),
  CONSTRAINT `fk_TIRO_RONDA1`
    FOREIGN KEY (`RONDA_numRonda`)
    REFERENCES `mydb`.`RONDA` (`numRonda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TIRO_PARTICIPANTE1`
    FOREIGN KEY (`PARTICIPANTE_EQUIPO_clvEquipo` , `PARTICIPANTE_clvPart`)
    REFERENCES `mydb`.`PARTICIPANTE` (`EQUIPO_clvEquipo` , `clvPart`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PACAPARTIDO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PACAPARTIDO` (
  `PACA_numPaca` INT AUTO_INCREMENT NOT NULL,
  `PARTIDO_clvPartido` INT NOT NULL,
  PRIMARY KEY (`PACA_numPaca`, `PARTIDO_clvPartido`),
  INDEX `fk_PACAPARTIDO_PARTIDO1_idx` (`PARTIDO_clvPartido` ASC),
  CONSTRAINT `fk_PACAPARTIDO_PACA1`
    FOREIGN KEY (`PACA_numPaca`)
    REFERENCES `mydb`.`PACA` (`numPaca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PACAPARTIDO_PARTIDO1`
    FOREIGN KEY (`PARTIDO_clvPartido`)
    REFERENCES `mydb`.`PARTIDO` (`clvPartido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
